name: HACS Validation

on:
  push:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: HACS validation
        uses: hacs/action@main
      - name: Home Assistant Config Check
        uses: frenck/action-home-assistant@v1
